# .goreleaser.yaml
version: 2
project_name: hashnode-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: hn-build
    main: ./cmd/hashnode-cli
    # BINARY NAME: The executable file will be named 'hn'
    binary: hn
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^merge:'

# -------------------------------------------------------------------------
# Scoop (Windows)
# -------------------------------------------------------------------------
scoops:
  - name: hn
    repository:
      owner: adil-adysh
      name: scoop-bucket
      branch: main
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    directory: bucket
    commit_author:
      name: goreleaser
      email: noreply@goreleaser.com
    description: "Unofficial Hashnode CLI - Write and manage blogs from your terminal."
    homepage: "https://github.com/adil-adysh/hashnode-cli"
    license: "Apache-2.0"

# -------------------------------------------------------------------------
# Snapcraft (Linux Snap Store)
# -------------------------------------------------------------------------
snapcrafts:
  - id: hn-snap
    ids:
      - hn-build
    
    # SNAP NAME: Must match the name you registered: 'hashnode-cli'
    name: hashnode-cli
    
    summary: "Unofficial CLI for Hashnode"
    description: |
      A community-built CLI for Hashnode. Write, manage, and publish your
      Hashnode blogs directly from your terminal. 
      (Unofficial tool, not affiliated with Hashnode).
    
    grade: stable
    channel_templates:
      - stable
    
    # Strict confinement = Automated security checks (no manual review needed)
    confinement: strict
    base: core22
    license: Apache-2.0
    
    # APP MAPPING: The snap is 'hashnode-cli', but the command users type is 'hn'
    apps:
      hn:
        command: hn
        plugs:
          - home
          - network
          - removable-media
    
    publish: true

# -------------------------------------------------------------------------
# NFPM (.deb / .rpm)
# -------------------------------------------------------------------------
nfpms:
  - id: hn-packages
    # PACKAGE NAME: Users install via 'apt install hn'
    package_name: hn
    
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Arch }}"
    vendor: "Adil Adysh"
    homepage: "https://github.com/adil-adysh/hashnode-cli"
    maintainer: "Adil Adysh <ah.shaikh97@gmail.com>"
    description: "Unofficial Hashnode CLI for blogging from the terminal."
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/hn/copyright
        file_info:
          mode: 0644

# -------------------------------------------------------------------------
# GitHub Releases
# -------------------------------------------------------------------------
release:
  github:
    owner: adil-adysh
    name: hashnode-cli
  draft: false
  prerelease: auto