version: 2
project_name: hn
builds:
  - id: hn
    main: ./cmd/hashnode-cli
    binary: hn
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: archive
    ids:
      - hn
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: checksums.txt
changelog:
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
