// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package api

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// Contains information about banner image options of the post. Like URL of the banner image, attribution, etc.
type BannerImageOptionsInput struct {
	// The URL of the banner image.
	BannerImageURL string `json:"bannerImageURL"`
}

// GetBannerImageURL returns BannerImageOptionsInput.BannerImageURL, and is useful for accessing the field via an interface.
func (v *BannerImageOptionsInput) GetBannerImageURL() string { return v.BannerImageURL }

// Contains information about cover image options of the post. Like URL of the cover image, attribution, etc.
type CoverImageOptionsInput struct {
	// The URL of the cover image.
	CoverImageURL string `json:"coverImageURL"`
	// A flag to indicate if the cover attribution is hidden, used when cover was chosen from unsplash.
	IsCoverAttributionHidden bool `json:"isCoverAttributionHidden"`
	// Information about the cover image attribution.
	CoverImageAttribution string `json:"coverImageAttribution"`
	// The name of the cover image photographer, used when cover was chosen from unsplash.
	CoverImagePhotographer string `json:"coverImagePhotographer"`
	// A flag to indicate if the cover image is sticked to bottom.
	StickCoverToBottom bool `json:"stickCoverToBottom"`
}

// GetCoverImageURL returns CoverImageOptionsInput.CoverImageURL, and is useful for accessing the field via an interface.
func (v *CoverImageOptionsInput) GetCoverImageURL() string { return v.CoverImageURL }

// GetIsCoverAttributionHidden returns CoverImageOptionsInput.IsCoverAttributionHidden, and is useful for accessing the field via an interface.
func (v *CoverImageOptionsInput) GetIsCoverAttributionHidden() bool {
	return v.IsCoverAttributionHidden
}

// GetCoverImageAttribution returns CoverImageOptionsInput.CoverImageAttribution, and is useful for accessing the field via an interface.
func (v *CoverImageOptionsInput) GetCoverImageAttribution() string { return v.CoverImageAttribution }

// GetCoverImagePhotographer returns CoverImageOptionsInput.CoverImagePhotographer, and is useful for accessing the field via an interface.
func (v *CoverImageOptionsInput) GetCoverImagePhotographer() string { return v.CoverImagePhotographer }

// GetStickCoverToBottom returns CoverImageOptionsInput.StickCoverToBottom, and is useful for accessing the field via an interface.
func (v *CoverImageOptionsInput) GetStickCoverToBottom() bool { return v.StickCoverToBottom }

// GetPublicationPublication includes the requested fields of the GraphQL type Publication.
// The GraphQL type's documentation follows.
//
// Contains basic information about the publication.
// A publication is a blog that can be created for a user or a team.
type GetPublicationPublication struct {
	// The title of the publication.
	// Title is used as logo if logo is not provided.
	Title string `json:"title"`
	// Returns the list of posts in the publication.
	Posts GetPublicationPublicationPostsPublicationPostConnection `json:"posts"`
}

// GetTitle returns GetPublicationPublication.Title, and is useful for accessing the field via an interface.
func (v *GetPublicationPublication) GetTitle() string { return v.Title }

// GetPosts returns GetPublicationPublication.Posts, and is useful for accessing the field via an interface.
func (v *GetPublicationPublication) GetPosts() GetPublicationPublicationPostsPublicationPostConnection {
	return v.Posts
}

// GetPublicationPublicationPostsPublicationPostConnection includes the requested fields of the GraphQL type PublicationPostConnection.
// The GraphQL type's documentation follows.
//
// Connection for posts within a publication. Contains a list of edges containing nodes.
// Each node is a post.
// Page info contains information about pagination like hasNextPage and endCursor.
type GetPublicationPublicationPostsPublicationPostConnection struct {
	// A list of edges containing Post information
	Edges []GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdge `json:"edges"`
}

// GetEdges returns GetPublicationPublicationPostsPublicationPostConnection.Edges, and is useful for accessing the field via an interface.
func (v *GetPublicationPublicationPostsPublicationPostConnection) GetEdges() []GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdge {
	return v.Edges
}

// GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdge includes the requested fields of the GraphQL type PostEdge.
// The GraphQL type's documentation follows.
//
// Contains a post and a cursor for pagination.
type GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdge struct {
	// The node holding the Post information
	Node GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdgeNodePost `json:"node"`
}

// GetNode returns GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdge.Node, and is useful for accessing the field via an interface.
func (v *GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdge) GetNode() GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdgeNodePost {
	return v.Node
}

// GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdgeNodePost includes the requested fields of the GraphQL type Post.
// The GraphQL type's documentation follows.
//
// Contains basic information about the post.
// A post is a published article on Hashnode.
type GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdgeNodePost struct {
	// The ID of the post. Used to uniquely identify the post.
	Id string `json:"id"`
	// The title of the post.
	Title string `json:"title"`
}

// GetId returns GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdgeNodePost.Id, and is useful for accessing the field via an interface.
func (v *GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdgeNodePost) GetId() string {
	return v.Id
}

// GetTitle returns GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdgeNodePost.Title, and is useful for accessing the field via an interface.
func (v *GetPublicationPublicationPostsPublicationPostConnectionEdgesPostEdgeNodePost) GetTitle() string {
	return v.Title
}

// GetPublicationResponse is returned by GetPublication on success.
type GetPublicationResponse struct {
	// Returns the publication with the given ID or host.
	// User can pass anyone of them.
	Publication GetPublicationPublication `json:"publication"`
}

// GetPublication returns GetPublicationResponse.Publication, and is useful for accessing the field via an interface.
func (v *GetPublicationResponse) GetPublication() GetPublicationPublication { return v.Publication }

// Contains information about meta tags. Used for SEO purpose.
type MetaTagsInput struct {
	// The title of the post used in og:title for SEO.
	Title string `json:"title"`
	// The description of the post used in og:description for SEO.
	Description string `json:"description"`
	// The image URL of the post used in og:image for SEO.
	Image string `json:"image"`
}

// GetTitle returns MetaTagsInput.Title, and is useful for accessing the field via an interface.
func (v *MetaTagsInput) GetTitle() string { return v.Title }

// GetDescription returns MetaTagsInput.Description, and is useful for accessing the field via an interface.
func (v *MetaTagsInput) GetDescription() string { return v.Description }

// GetImage returns MetaTagsInput.Image, and is useful for accessing the field via an interface.
func (v *MetaTagsInput) GetImage() string { return v.Image }

type PublishPostTagInput struct {
	// A tag id that is referencing an existing tag.
	//
	// Either this or name and slug should be provided. If both are provided, the id will be used.
	Id string `json:"id"`
	// A slug of a new tag to create.
	//
	// Either this and name or id should be provided. If both are provided, the id will be used.
	Slug string `json:"slug"`
	// A name of a new tag to create.
	//
	// Either this and slug or id should be provided. If both are provided, the id will be used.
	Name string `json:"name"`
}

// GetId returns PublishPostTagInput.Id, and is useful for accessing the field via an interface.
func (v *PublishPostTagInput) GetId() string { return v.Id }

// GetSlug returns PublishPostTagInput.Slug, and is useful for accessing the field via an interface.
func (v *PublishPostTagInput) GetSlug() string { return v.Slug }

// GetName returns PublishPostTagInput.Name, and is useful for accessing the field via an interface.
func (v *PublishPostTagInput) GetName() string { return v.Name }

type UpdatePostInput struct {
	// The id of the post to update.
	Id string `json:"id"`
	// The new title of the post
	Title string `json:"title"`
	// The subtitle of the post
	Subtitle string `json:"subtitle"`
	// The publication the post is published to.
	ContentMarkdown string `json:"contentMarkdown"`
	// Backdated publish date.
	PublishedAt time.Time `json:"publishedAt"`
	// Options for the cover image of the post.
	CoverImageOptions CoverImageOptionsInput `json:"coverImageOptions"`
	// Options for the banner image of the post.
	BannerImageOptions BannerImageOptionsInput `json:"bannerImageOptions"`
	// Slug of the post. Only if you want to override the slug that will be generated based on the title.
	Slug string `json:"slug"`
	// Canonical URL of the original article.
	OriginalArticleURL string `json:"originalArticleURL"`
	// Tags to add to the post. New tags will be created if they don't exist. It overrides the existing tags.
	Tags []PublishPostTagInput `json:"tags"`
	// Information about the meta tags added to the post, used for SEO purpose.
	MetaTags MetaTagsInput `json:"metaTags"`
	// Set a different author for the post than the requesting user.
	// Must be a member of the publication.
	PublishAs string `json:"publishAs"`
	// Update co-authors of the post.
	// Must be a member of the publication.
	CoAuthors []string `json:"coAuthors"`
	// Providing a seriesId will add the post to that series.
	// Must be a series of the publication.
	SeriesId string `json:"seriesId"`
	// Whether or not to enable the table of content.
	Settings UpdatePostSettingsInput `json:"settings"`
	// If the publication should be changed this is the new Publication ID
	PublicationId string `json:"publicationId"`
}

// GetId returns UpdatePostInput.Id, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetId() string { return v.Id }

// GetTitle returns UpdatePostInput.Title, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetTitle() string { return v.Title }

// GetSubtitle returns UpdatePostInput.Subtitle, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetSubtitle() string { return v.Subtitle }

// GetContentMarkdown returns UpdatePostInput.ContentMarkdown, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetContentMarkdown() string { return v.ContentMarkdown }

// GetPublishedAt returns UpdatePostInput.PublishedAt, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetPublishedAt() time.Time { return v.PublishedAt }

// GetCoverImageOptions returns UpdatePostInput.CoverImageOptions, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetCoverImageOptions() CoverImageOptionsInput { return v.CoverImageOptions }

// GetBannerImageOptions returns UpdatePostInput.BannerImageOptions, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetBannerImageOptions() BannerImageOptionsInput {
	return v.BannerImageOptions
}

// GetSlug returns UpdatePostInput.Slug, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetSlug() string { return v.Slug }

// GetOriginalArticleURL returns UpdatePostInput.OriginalArticleURL, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetOriginalArticleURL() string { return v.OriginalArticleURL }

// GetTags returns UpdatePostInput.Tags, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetTags() []PublishPostTagInput { return v.Tags }

// GetMetaTags returns UpdatePostInput.MetaTags, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetMetaTags() MetaTagsInput { return v.MetaTags }

// GetPublishAs returns UpdatePostInput.PublishAs, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetPublishAs() string { return v.PublishAs }

// GetCoAuthors returns UpdatePostInput.CoAuthors, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetCoAuthors() []string { return v.CoAuthors }

// GetSeriesId returns UpdatePostInput.SeriesId, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetSeriesId() string { return v.SeriesId }

// GetSettings returns UpdatePostInput.Settings, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetSettings() UpdatePostSettingsInput { return v.Settings }

// GetPublicationId returns UpdatePostInput.PublicationId, and is useful for accessing the field via an interface.
func (v *UpdatePostInput) GetPublicationId() string { return v.PublicationId }

// UpdatePostResponse is returned by UpdatePost on success.
type UpdatePostResponse struct {
	UpdatePost UpdatePostUpdatePostUpdatePostPayload `json:"updatePost"`
}

// GetUpdatePost returns UpdatePostResponse.UpdatePost, and is useful for accessing the field via an interface.
func (v *UpdatePostResponse) GetUpdatePost() UpdatePostUpdatePostUpdatePostPayload {
	return v.UpdatePost
}

type UpdatePostSettingsInput struct {
	// A flag to indicate if the post contains table of content
	IsTableOfContentEnabled bool `json:"isTableOfContentEnabled"`
	// A flag to indicate if the post is delisted, used to hide the post from public feed.
	Delisted bool `json:"delisted"`
	// Whether or not comments should be disabled.
	DisableComments bool `json:"disableComments"`
	// Pin the post to the blog homepage.
	PinToBlog bool `json:"pinToBlog"`
}

// GetIsTableOfContentEnabled returns UpdatePostSettingsInput.IsTableOfContentEnabled, and is useful for accessing the field via an interface.
func (v *UpdatePostSettingsInput) GetIsTableOfContentEnabled() bool { return v.IsTableOfContentEnabled }

// GetDelisted returns UpdatePostSettingsInput.Delisted, and is useful for accessing the field via an interface.
func (v *UpdatePostSettingsInput) GetDelisted() bool { return v.Delisted }

// GetDisableComments returns UpdatePostSettingsInput.DisableComments, and is useful for accessing the field via an interface.
func (v *UpdatePostSettingsInput) GetDisableComments() bool { return v.DisableComments }

// GetPinToBlog returns UpdatePostSettingsInput.PinToBlog, and is useful for accessing the field via an interface.
func (v *UpdatePostSettingsInput) GetPinToBlog() bool { return v.PinToBlog }

// UpdatePostUpdatePostUpdatePostPayload includes the requested fields of the GraphQL type UpdatePostPayload.
type UpdatePostUpdatePostUpdatePostPayload struct {
	Post UpdatePostUpdatePostUpdatePostPayloadPost `json:"post"`
}

// GetPost returns UpdatePostUpdatePostUpdatePostPayload.Post, and is useful for accessing the field via an interface.
func (v *UpdatePostUpdatePostUpdatePostPayload) GetPost() UpdatePostUpdatePostUpdatePostPayloadPost {
	return v.Post
}

// UpdatePostUpdatePostUpdatePostPayloadPost includes the requested fields of the GraphQL type Post.
// The GraphQL type's documentation follows.
//
// Contains basic information about the post.
// A post is a published article on Hashnode.
type UpdatePostUpdatePostUpdatePostPayloadPost struct {
	// The ID of the post. Used to uniquely identify the post.
	Id string `json:"id"`
	// The slug of the post. Used as address of the post on blog. Example - https://johndoe.com/my-post-slug
	Slug string `json:"slug"`
	// The date and time the post was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetId returns UpdatePostUpdatePostUpdatePostPayloadPost.Id, and is useful for accessing the field via an interface.
func (v *UpdatePostUpdatePostUpdatePostPayloadPost) GetId() string { return v.Id }

// GetSlug returns UpdatePostUpdatePostUpdatePostPayloadPost.Slug, and is useful for accessing the field via an interface.
func (v *UpdatePostUpdatePostUpdatePostPayloadPost) GetSlug() string { return v.Slug }

// GetUpdatedAt returns UpdatePostUpdatePostUpdatePostPayloadPost.UpdatedAt, and is useful for accessing the field via an interface.
func (v *UpdatePostUpdatePostUpdatePostPayloadPost) GetUpdatedAt() time.Time { return v.UpdatedAt }

// __GetPublicationInput is used internally by genqlient
type __GetPublicationInput struct {
	Id string `json:"id"`
}

// GetId returns __GetPublicationInput.Id, and is useful for accessing the field via an interface.
func (v *__GetPublicationInput) GetId() string { return v.Id }

// __UpdatePostInput is used internally by genqlient
type __UpdatePostInput struct {
	Input UpdatePostInput `json:"input"`
}

// GetInput returns __UpdatePostInput.Input, and is useful for accessing the field via an interface.
func (v *__UpdatePostInput) GetInput() UpdatePostInput { return v.Input }

// The query executed by GetPublication.
const GetPublication_Operation = `
query GetPublication ($id: ObjectId!) {
	publication(id: $id) {
		title
		posts(first: 20) {
			edges {
				node {
					id
					title
				}
			}
		}
	}
}
`

func GetPublication(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetPublicationResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetPublication",
		Query:  GetPublication_Operation,
		Variables: &__GetPublicationInput{
			Id: id,
		},
	}

	data_ = &GetPublicationResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by UpdatePost.
const UpdatePost_Operation = `
mutation UpdatePost ($input: UpdatePostInput!) {
	updatePost(input: $input) {
		post {
			id
			slug
			updatedAt
		}
	}
}
`

func UpdatePost(
	ctx_ context.Context,
	client_ graphql.Client,
	input UpdatePostInput,
) (data_ *UpdatePostResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UpdatePost",
		Query:  UpdatePost_Operation,
		Variables: &__UpdatePostInput{
			Input: input,
		},
	}

	data_ = &UpdatePostResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
